# Generated by Django 5.1.1 on 2024-09-13 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='designation',
        ),
    ]
