# Generated by Django 5.1.1 on 2024-09-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0002_remove_task_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='designation',
            field=models.CharField(default=True, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
